#!/bin/bash

# Syncing script for Mac to USB/SD drive for UConnect

# Syncs all music from iTunes to the USB drive, and fixes
# any exported iTunes playlists. Playlists should be exported
# to the directory referenced by $playlistdir

# Will sync everything but iTunes LPs and videos.

# Change this to your USB/SD card name.
volume=UCONNECT

# If you want your music in a different directory name, change this.
# Path is relative from root. Omit the trailing /.
musicdir=iTunes-Music

# If you want your playlists in a different directory name, change this.
# Path is relative from root. Omit the trailing /.
playlistdir=Playlists

# If you sometimes delete music from your library, and want to mirror
# those deletes to the target drive, set this to 1.
delete=0

src="$HOME/Music/iTunes/iTunes Media/Music/"
destroot="/Volumes/$volume"
dest="$destroot/$musicdir/"

if [ ! -d "$destroot" ]; then
	echo "Destination volume '$destroot' is not mounted."
	exit 1
fi

if [ ! -d "$dest" ]; then
	mkdir "$dest"
fi

deleteopt=""
if [ "$delete" -eq 1 ]; then
	deleteopt=--delete
fi

# Perform the sync. --modify-window works around FAT32 time rounding.
time rsync --archive --verbose --exclude='*.itlp' --exclude='.*' --exclude='*.m4v' --modify-window=1 $deleteopt "$src" "$dest"

# If playlists are there, translate them.
for file in "$destroot"/"$playlistdir"/*.m3u; do
	if [ -e "$file" ]; then
		# In case it's a URL-based playlist, a la Doug's Batch Export, remove the specifier.
		sed "s|file://||g" < "$file" > "$file.new" && mv "$file.new" "$file"
		sed "s|$src|/$musicdir/|g" < "$file" > "$file.new" && mv "$file.new" "$file"
	fi
done

# Clean up hidden files anywhere in the volume
find "$destroot" ! -name '.' -name '.*' -exec rm -rf {} \; 2>/dev/null

